substitutions:
  name: "wopr-env-sensor-v2"
  friendly_name: "Air Quality"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: Temperature, Pressure, Humidity, Gas, CO2, and Particulate Matter Sensor
  name_add_mac_suffix: true
  project:
    name: triplepoint.air-sensor
    version: "2.0"

logger:

api:

ota:

dashboard_import:
  package_import_url: github://triplepoint/wopr-air-quality-sensor/wopr-env-sensor-v2-esp32.yaml@main
  import_full_config: false

wifi:
  ap:
    password: "123dontpwnme"

captive_portal:

####

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: arduino

i2c:
  sda: 41
  scl: 40
  scan: true
  id: stemma

bme680_bsec:

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
      filters:
        - median
    pressure:
      name: "BME680 Pressure"
      id: bme_pressure
      filters:
        - median
    humidity:
      name: "BME680 Humidity"
      filters:
        - median
    gas_resistance:
      name: "BME680 Gas Resistance"
      filters:
        - median
    iaq:
      name: "BME680 IAQ"
      filters:
        - median
    iaq_accuracy:
      name: "BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"
      filters:
        - median
    address: 0x77

  - platform: scd4x
    ambient_pressure_compensation_source: bme_pressure
    co2:
      name: "SCD4X CO2"
    temperature:
      name: "SCD4X Temperature"
    humidity:
      name: "SCD4X Humidity"

  - platform: pmsa003i
    pm_1_0:
      name: "PM1.0"
    pm_2_5:
      name: "PM2.5"
    pm_10_0:
      name: "PM10.0"
    pmc_0_3:
      name: "PMC <0.3µm"
    pmc_0_5:
      name: "PMC <0.5µm"
    pmc_1_0:
      name: "PMC <1µm"
    pmc_2_5:
      name: "PMC <2.5µm"
    pmc_5_0:
      name: "PMC <5µm"
    pmc_10_0:
      name: "PMC <10µm"
