esphome:
  name: "wopr-env-sensor-v2"
  friendly_name: "Air Quality"
  comment: Temperature, Pressure, Humidity, Gas, CO2, and Particulate Matter Sensor
  name_add_mac_suffix: true

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ap:

captive_portal:

web_server:
  port: 80
  ota: false
  version: 3

####

i2c:
  sda: 41
  scl: 40
  scan: true
  id: stemma

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  temperature_offset: 6.9

text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
      id: bme_pressure
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    iaq_static:
      name: "BME680 IAQ"
      id: iaq

  - platform: scd4x
    ambient_pressure_compensation_source: bme_pressure
    temperature_offset: 0
    co2:
      name: "SCD4X CO2"
    temperature:
      name: "SCD4X Temperature"
    humidity:
      name: "SCD4X Humidity"

  - platform: pmsa003i
    pm_1_0:
      name: "PM1.0"
    pm_2_5:
      name: "PM2.5"
    pm_10_0:
      name: "PM10.0"
    pmc_0_3:
      name: "PMC <0.3µm"
    pmc_0_5:
      name: "PMC <0.5µm"
    pmc_1_0:
      name: "PMC <1µm"
    pmc_2_5:
      name: "PMC <2.5µm"
    pmc_5_0:
      name: "PMC <5µm"
    pmc_10_0:
      name: "PMC <10µm"
