esphome:
  name: "wopr-env-sensor-v1"
  friendly_name: "Air Quality"
  comment: Temperature, Pressure, Humidity, CO2, and Particulate Matter Sensor
  name_add_mac_suffix: true
  includes:
    - aqi_calc.h

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ap:

captive_portal:

web_server:
  port: 80
  ota: false
  version: 3

####

i2c:
  sda: 41
  scl: 40
  scan: true
  id: stemma

sensor:
  - platform: bme280_i2c
    address: 0x77
    update_interval: 60s
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
      id: bme_pressure
    humidity:
      name: "BME280 Humidity"

  - platform: scd4x
    ambient_pressure_compensation_source: bme_pressure
    temperature_offset: 0
    co2:
      name: "SCD4X CO2"
    temperature:
      name: "SCD4X Temperature"
    humidity:
      name: "SCD4X Humidity"

    # This template sensor is updated when the pmsa003i's pm_2_5 value updates below
  - platform: template
    name: "AQI (pm2.5)"
    id: pm_2_5_aqi
    update_interval: never
    state_class: measurement
    device_class: aqi
    accuracy_decimals: 0

    # This template sensor is updated when the pmsa003i's pm_10_0 value updates below
  - platform: template
    name: "AQI (pm10.0)"
    id: pm_10_0_aqi
    update_interval: never
    state_class: measurement
    device_class: aqi
    accuracy_decimals: 0

  - platform: pmsa003i
    pm_1_0:
      name: "PM1.0"
    pm_2_5:
      name: "PM2.5"
      on_value:
        - sensor.template.publish:
            id: pm_2_5_aqi
            state: !lambda 'return aqi_pm2_5(x);'
    pm_10_0:
      name: "PM10.0"
      on_value:
        - sensor.template.publish:
            id: pm_10_0_aqi
            state: !lambda 'return aqi_pm_10_0(x);'
    pmc_0_3:
      name: "PMC <0.3µm"
    pmc_0_5:
      name: "PMC <0.5µm"
    pmc_1_0:
      name: "PMC <1µm"
    pmc_2_5:
      name: "PMC <2.5µm"
    pmc_5_0:
      name: "PMC <5µm"
    pmc_10_0:
      name: "PMC <10µm"
