substitutions:
  name: "wopr-env-sensor-v1"
  friendly_name: "Air Quality"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: Temperature, Pressure, Humidity, CO2, and Particulate Matter Sensor
  name_add_mac_suffix: true
  project:
    name: triplepoint.air-sensor
    version: "1.0"

logger:

api:

ota:
  platform: esphome

dashboard_import:
  package_import_url: github://triplepoint/wopr-air-quality-sensor/wopr-env-sensor-v1-esp32.yaml@main
  import_full_config: false

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "123dontpwnme"

captive_portal:

web_server:
  port: 80
  ota: false
  version: 3

####

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: arduino

i2c:
  sda: 41
  scl: 40
  scan: true
  id: stemma

sensor:
  - platform: bme280_i2c
    address: 0x77
    update_interval: 60s
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
      id: bme_pressure
    humidity:
      name: "BME280 Humidity"

  - platform: scd4x
    ambient_pressure_compensation_source: bme_pressure
    temperature_offset: 0
    co2:
      name: "SCD4X CO2"
    temperature:
      name: "SCD4X Temperature"
    humidity:
      name: "SCD4X Humidity"

  - platform: pmsa003i
    pm_1_0:
      name: "PM1.0"
    pm_2_5:
      name: "PM2.5"
    pm_10_0:
      name: "PM10.0"
    pmc_0_3:
      name: "PMC <0.3µm"
    pmc_0_5:
      name: "PMC <0.5µm"
    pmc_1_0:
      name: "PMC <1µm"
    pmc_2_5:
      name: "PMC <2.5µm"
    pmc_5_0:
      name: "PMC <5µm"
    pmc_10_0:
      name: "PMC <10µm"
