name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: wopr-env-sensor-v1-esp32.yaml,wopr-env-sensor-v2-esp32.yaml
      name: Wopr Environment Sensor
